packages:
  - 'packages/*'
  - 'docs'
  - 'crates/tauri-plugin-holochain-service'
  - 'crates/tauri-plugin-holochain-service/examples/tauri-app'
  - 'crates/tauri-plugin-holochain-service-consumer'
  - 'crates/tauri-plugin-holochain-service-consumer/examples/tauri-app'
