[default]
description = "Default permissions for the plugin"
permissions = ["allow-launch", "allow-shutdown", "allow-get-admin-port", "allow-install-app", "allow-uninstall-app", "allow-enable-app", "allow-disable-app", "allow-list-installed-apps", "allow-is-app-installed", "allow-app-websocket-auth", "allow-sign-zome-call"]
